---
# vars file for deploy_k8s_csi
#vsphere_cpi_url:  "https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/release-{{ k8s_version_short.split('.')[0:2]|join('.') }}/releases/v{{ k8s_version_short.split('.')[0:2]|join('.') }}/vsphere-cloud-controller-manager.yaml"
                #  https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/refs/heads/master/releases/v1.30/vsphere-cloud-controller-manager.yaml
vsphere_cpi_url: https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/refs/heads/master/releases/v{{ k8s_version_short.split('.')[0:2]|join('.') }}/vsphere-cloud-controller-manager.yaml


                   
#vsphere_csi_manifest_url: "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/{{ vsphere_csi_driver_version }}/manifests/vanilla/vsphere-csi-driver.yaml"
#                           https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/refs/tags/v3.3.1/manifests/vanilla/vsphere-csi-driver.yaml

vsphere_csi_manifest_url: "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/refs/tags/v3.3.1/manifests/vanilla/vsphere-csi-driver.yaml"

# vsphere_csi_driver_version: v3.3.1
