---
- name: "create folder for coredns backups and patched config"
  file:
    path: "/home/{{ os_admin_username }}/coredns_cfg/"
    state: directory
    owner: kuberadm
    group: kuberadm
    mode: '0744'

- name: "backup and delete coredns config map"
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf -n kube-system get cm coredns -o yaml > /home/"{{ os_admin_username }}"/coredns_cfg/coredns_cm.bkp
    kubectl --kubeconfig=/etc/kubernetes/admin.conf -n kube-system delete cm coredns

- name: "copy new coredns cm with custom 'hosts' block"
  template:
    src: "coredns_fix_{{ cloud_type }}.yaml.j2"
    dest: "/home/{{ os_admin_username }}/coredns_cfg/coredns_fix.yaml"

- name: "backup and delete coredns config map"
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf -n kube-system create -f "/home/{{ os_admin_username }}/coredns_cfg/coredns_fix.yaml"
    kubectl --kubeconfig=/etc/kubernetes/admin.conf -n kube-system rollout restart deployment coredns

- name: "wait 30 sec and get coredns status"
  shell: |
    sleep 30
    kubectl --kubeconfig=/etc/kubernetes/admin.conf -n kube-system get pod | grep coredns
  register: corednspods_state

- name: "show coredns pod's state"
  debug:
    msg: "corednspods_state.stdout_lines"

...