  - name: "create directory's for etcd backup files on every master"
    file:
      path: "/etcd_backup"
      state: directory
      owner: kuberadm
      group: kuberadm
      mode: '2744'
 
  - name: "copy backup script to /opt/"
    copy:
      src: etcd_backup_script.sh
      dest: /opt/etcd_backup_script.sh
      mode: '0755'
  
  - name: "Execute ETCD Backup Script"
    shell:
      cmd: /opt/etcd_backup_script.sh
  
  - name: "Enable public key authentication on masters" # to allow backupsvc connect       
    replace:
      path: /etc/ssh/sshd_config
      regexp: "#PubkeyAuthentication"
      replace: "PubkeyAuthentication"
  
  - name: "restart sshd after enabling public key authentication"
    ansible.builtin.service:
      name: sshd
      state: restarted
    
 

